-- Seed the complete Agent Types Taxonomy (55+ reusable intelligence archetypes)
TRUNCATE TABLE agent_types CASCADE;

INSERT INTO agent_types (key, name, description, capabilities, is_active)
VALUES 
('orchestrator', 'Orchestrator', 'Coordinates other agents, teams, and workflows', '["coordination", "routing", "synthesis"]'::jsonb, true),
('advisor', 'Advisor', 'Provides recommendations and guidance', '["advisory", "guidance"]'::jsonb, true),
('analyst', 'Analyst', 'Examines information and identifies patterns', '["analysis", "pattern_recognition"]'::jsonb, true),
('researcher', 'Researcher', 'Finds, gathers, validates, and synthesizes information', '["research", "validation"]'::jsonb, true),
('interpreter', 'Interpreter', 'Converts complex information into meaningful insights', '["interpretation", "insight"]'::jsonb, true),
('strategist', 'Strategist', 'Develops plans and long-range direction', '["strategy", "planning"]'::jsonb, true),
('planner', 'Planner', 'Converts objectives into actionable plans', '["planning", "structuring"]'::jsonb, true),
('decision_agent', 'Decision Agent', 'Evaluates options and makes authorized decisions', '["decision_making", "evaluation"]'::jsonb, true),
('predictor', 'Predictor', 'Forecasts likely outcomes', '["prediction", "forecasting"]'::jsonb, true),
('diagnostician', 'Diagnostician', 'Identifies problems, causes, and conditions', '["diagnosis", "troubleshooting"]'::jsonb, true),
('evaluator', 'Evaluator', 'Scores, assesses, audits, or benchmarks', '["evaluation", "auditing"]'::jsonb, true),
('validator', 'Validator', 'Checks accuracy, completeness, and compliance', '["validation", "compliance"]'::jsonb, true),
('monitor', 'Monitor', 'Watches systems, metrics, events, and changes', '["monitoring", "alerting"]'::jsonb, true),
('optimizer', 'Optimizer', 'Improves performance, efficiency, or outcomes', '["optimization", "refinement"]'::jsonb, true),
('executor', 'Executor', 'Performs an assigned task', '["execution", "task_handling"]'::jsonb, true),
('automation_agent', 'Automation Agent', 'Executes automated processes', '["automation", "workflow"]'::jsonb, true),
('coordinator', 'Coordinator', 'Manages dependencies between people, agents, and tasks', '["coordination", "management"]'::jsonb, true),
('communicator', 'Communicator', 'Handles messaging and information exchange', '["communication", "messaging"]'::jsonb, true),
('educator', 'Educator', 'Teaches and explains', '["education", "explanation"]'::jsonb, true),
('coach', 'Coach', 'Guides development and behavior', '["coaching", "development"]'::jsonb, true),
('mentor', 'Mentor', 'Provides longer-term developmental guidance', '["mentorship", "guidance"]'::jsonb, true),
('creator', 'Creator', 'Generates content, ideas, assets, or solutions', '["creation", "generation"]'::jsonb, true),
('designer', 'Designer', 'Designs experiences, systems, strategies, or assets', '["design", "architecture"]'::jsonb, true),
('curator', 'Curator', 'Selects, organizes, and prioritizes information', '["curation", "organization"]'::jsonb, true),
('classifier', 'Classifier', 'Categorizes information', '["classification", "sorting"]'::jsonb, true),
('extractor', 'Extractor', 'Pulls structured information from unstructured data', '["extraction", "parsing"]'::jsonb, true),
('transformer', 'Transformer', 'Converts information from one form into another', '["transformation", "conversion"]'::jsonb, true),
('synthesizer', 'Synthesizer', 'Combines multiple sources or agents into one result', '["synthesis", "integration"]'::jsonb, true),
('negotiator', 'Negotiator', 'Handles competing interests or objectives', '["negotiation", "mediation"]'::jsonb, true),
('mediator', 'Mediator', 'Resolves conflicts', '["conflict_resolution", "mediation"]'::jsonb, true),
('guardian', 'Guardian', 'Protects defined resources, rules, or boundaries', '["protection", "security"]'::jsonb, true),
('compliance_agent', 'Compliance Agent', 'Checks regulatory and policy requirements', '["compliance", "governance"]'::jsonb, true),
('security_agent', 'Security Agent', 'Protects systems, data, and permissions', '["security", "protection"]'::jsonb, true),
('memory_agent', 'Memory Agent', 'Manages persistent and contextual memory', '["memory", "retrieval"]'::jsonb, true),
('knowledge_agent', 'Knowledge Agent', 'Manages organizational and domain knowledge', '["knowledge", "indexing"]'::jsonb, true),
('interface_agent', 'Interface Agent', 'Serves as the interaction layer', '["interface", "interaction"]'::jsonb, true),
('liaison', 'Liaison', 'Connects different people, teams, systems, or entities', '["liaison", "connection"]'::jsonb, true),
('supervisor', 'Supervisor', 'Reviews and oversees other agents', '["supervision", "oversight"]'::jsonb, true),
('auditor', 'Auditor', 'Independently examines activity and results', '["auditing", "verification"]'::jsonb, true),
('recovery_agent', 'Recovery Agent', 'Handles failures and restoration', '["recovery", "restoration"]'::jsonb, true),
('learning_agent', 'Learning Agent', 'Identifies lessons and improves system behavior', '["learning", "adaptation"]'::jsonb, true),
('certification_agent', 'Certification Agent', 'Tests and certifies agents, users, and systems', '["certification", "testing"]'::jsonb, true),
('deployment_agent', 'Deployment Agent', 'Prepares and deploys intelligence', '["deployment", "provisioning"]'::jsonb, true),
('simulation_agent', 'Simulation Agent', 'Models hypothetical situations', '["simulation", "modeling"]'::jsonb, true),
('testing_agent', 'Testing Agent', 'Tests functionality and behavior', '["testing", "qa"]'::jsonb, true),
('triage_agent', 'Triage Agent', 'Determines priority and routing', '["triage", "prioritization"]'::jsonb, true),
('intake_agent', 'Intake Agent', 'Receives and structures incoming requests', '["intake", "structuring"]'::jsonb, true),
('routing_agent', 'Routing Agent', 'Sends work to the appropriate intelligence', '["routing", "dispatch"]'::jsonb, true),
('escalation_agent', 'Escalation Agent', 'Moves issues to higher authority', '["escalation", "management"]'::jsonb, true),
('reporting_agent', 'Reporting Agent', 'Produces reports and summaries', '["reporting", "summarization"]'::jsonb, true),
('reconciliation_agent', 'Reconciliation Agent', 'Resolves differences between records or results', '["reconciliation", "matching"]'::jsonb, true),
('procurement_agent', 'Procurement Agent', 'Sources and evaluates required resources', '["procurement", "sourcing"]'::jsonb, true),
('transaction_agent', 'Transaction Agent', 'Executes authorized transactions', '["transaction", "execution"]'::jsonb, true),
('relationship_agent', 'Relationship Agent', 'Manages relationship intelligence', '["relationship", "engagement"]'::jsonb, true),
('growth_agent', 'Growth Agent', 'Identifies and executes growth opportunities', '["growth", "expansion"]'::jsonb, true)
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
