-- Create intelligence_engines table to support the 128 intelligence engines architecture
CREATE TABLE IF NOT EXISTS intelligence_engines (
  engine_id VARCHAR(32) PRIMARY KEY,
  engine_name VARCHAR(128) NOT NULL,
  family VARCHAR(64) NOT NULL,
  description TEXT,
  config JSONB DEFAULT '{}'::jsonb,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed the 128 Canonical Archetypes (V2.0 Naming Pass, deduplicated)
TRUNCATE TABLE archetypes CASCADE;

INSERT INTO archetypes (archetype_id, archetype_name, description, category, base_capability, base_trust, base_synergy, base_activation, base_evolution, base_risk, default_avatar, default_decision_mode)
VALUES 
-- I. IDENTITY & SELF (AR-001 to AR-016)
('AR-001', 'The Sovereign', 'Takes full responsibility for choices, direction, energy, and life.', 'Identity & Self', 95, 95, 80, 90, 98, 5, 'eden', 'ADVISORY'),
('AR-002', 'The Lover', 'Approaches life through intimacy, devotion, appreciation, and deep connection.', 'Identity & Self', 88, 92, 95, 85, 90, 10, 'eden', 'ADVISORY'),
('AR-003', 'The Warrior', 'Develops courage, discipline, resilience, and the ability to act under pressure.', 'Identity & Self', 90, 90, 85, 90, 91, 25, 'eden', 'ADVISORY'),
('AR-004', 'The Seeker', 'Constantly pursues truth, meaning, understanding, and self-discovery.', 'Identity & Self', 88, 88, 85, 88, 94, 15, 'nova', 'ADVISORY'),
('AR-005', 'The Visionary', 'Sees the future before it becomes obvious and gives others a picture of what is possible.', 'Identity & Self', 92, 85, 90, 95, 94, 25, 'nova', 'ADVISORY'),
('AR-006', 'The Sage', 'Pursues wisdom and seeks to understand the deeper patterns behind life.', 'Identity & Self', 96, 92, 90, 80, 98, 5, 'nova', 'ADVISORY'),
('AR-007', 'The Mystic', 'Experiences reality through intuition, symbolism, consciousness, and the unseen.', 'Identity & Self', 90, 88, 85, 85, 95, 15, 'nova', 'ADVISORY'),
('AR-008', 'The Rebel', 'Challenges obsolete rules and refuses to participate in systems that suppress human potential.', 'Identity & Self', 85, 75, 70, 95, 90, 40, 'nova', 'ADVISORY'),
('AR-009', 'The Guardian', 'Maintains boundaries around people, places, traditions, and principles.', 'Identity & Self', 88, 98, 85, 85, 89, 20, 'nova', 'ADVISORY'),
('AR-010', 'The Individualist', 'Cultivates unique identity and sovereign expression independent of collective pressure.', 'Identity & Self', 86, 85, 78, 88, 92, 15, 'nova', 'ADVISORY'),
('AR-011', 'The Observer', 'Observes without immediately reacting, allowing reality to reveal itself clearly.', 'Identity & Self', 90, 95, 85, 75, 90, 5, 'nova', 'ADVISORY'),
('AR-012', 'The Dreamer', 'Allows imagination to reveal possibilities before practicality constrains them.', 'Identity & Self', 85, 80, 85, 90, 88, 20, 'nova', 'ADVISORY'),
('AR-013', 'The Realist', 'Anchors vision in practical constraints, evidence, and grounded mechanics.', 'Identity & Self', 90, 92, 88, 85, 85, 10, 'nova', 'ADVISORY'),
('AR-014', 'The Initiate', 'Willingly enters transformation and accepts the uncertainty of becoming someone new.', 'Identity & Self', 84, 82, 85, 92, 95, 30, 'nova', 'ADVISORY'),
('AR-015', 'The Elder', 'Represents maturity, perspective, patience, and accumulated wisdom.', 'Identity & Self', 94, 98, 92, 80, 96, 5, 'nova', 'ADVISORY'),
('AR-016', 'The Catalyst', 'Creates conditions that accelerate transformation in people and systems.', 'Identity & Self', 92, 85, 90, 95, 94, 25, 'nova', 'ADVISORY'),

-- II. CREATION & EXPRESSION (AR-017 to AR-032)
('AR-017', 'The Creator', 'Turns imagination into tangible reality through art, invention, business, or expression.', 'Creation & Expression', 90, 88, 92, 92, 95, 15, 'nova', 'ADVISORY'),
('AR-018', 'The Artist', 'Reveals new possibilities through beauty, expression, imagination, and emotion.', 'Creation & Expression', 88, 85, 90, 90, 92, 20, 'nova', 'ADVISORY'),
('AR-019', 'The Maker', 'Creates practical things that improve life and endure beyond the individual.', 'Creation & Expression', 90, 90, 88, 88, 90, 10, 'nova', 'ADVISORY'),
('AR-020', 'The Inventor', 'Creates tools, mechanisms, and approaches that did not previously exist.', 'Creation & Expression', 93, 88, 85, 92, 95, 20, 'nova', 'ADVISORY'),
('AR-021', 'The Storyteller', 'Uses narrative to preserve meaning, inspire action, and shape collective identity.', 'Creation & Expression', 89, 86, 92, 90, 91, 15, 'nova', 'ADVISORY'),
('AR-022', 'The Communicator', 'Carries important ideas between people, cultures, and communities with absolute clarity.', 'Creation & Expression', 88, 90, 90, 88, 88, 10, 'nova', 'ADVISORY'),
('AR-023', 'The Performer', 'Embodies presence, expression, and energetic transmission in live contexts.', 'Creation & Expression', 85, 82, 85, 92, 86, 25, 'nova', 'ADVISORY'),
('AR-024', 'The Designer', 'Creates experiences and environments intentionally rather than accidentally.', 'Creation & Expression', 91, 89, 92, 90, 93, 10, 'nova', 'ADVISORY'),
('AR-025', 'The Architect', 'Designs structures, systems, environments, and frameworks that allow life to thrive.', 'Creation & Expression', 95, 90, 92, 90, 94, 10, 'nova', 'ADVISORY'),
('AR-026', 'The Innovator', 'Introduces novel paradigms that shift industries and human behavior.', 'Creation & Expression', 92, 86, 88, 94, 95, 25, 'nova', 'ADVISORY'),
('AR-027', 'The Experimenter', 'Uses prototyping and testing to discover what works through direct experience.', 'Creation & Expression', 88, 85, 85, 92, 90, 20, 'nova', 'ADVISORY'),
('AR-028', 'The Curator', 'Selects and organizes meaningful things so others can discover their true value.', 'Creation & Expression', 87, 92, 90, 85, 89, 10, 'nova', 'ADVISORY'),
('AR-029', 'The Weaver', 'Integrates seemingly separate ideas, people, resources, and systems into a cohesive whole.', 'Creation & Expression', 90, 94, 95, 88, 93, 10, 'nova', 'ADVISORY'),
('AR-030', 'The Alchemist', 'Transforms adversity, raw potential, and difficult experiences into something valuable.', 'Creation & Expression', 94, 85, 88, 92, 96, 20, 'nova', 'ADVISORY'),
('AR-031', 'The Muse', 'Ignites inspiration, creative breakthrough, and aesthetic awakening in others.', 'Creation & Expression', 86, 90, 92, 85, 91, 15, 'nova', 'ADVISORY'),
('AR-032', 'The Vision Builder', 'Converts visionary blueprints into concrete operational frameworks.', 'Creation & Expression', 92, 90, 91, 90, 93, 12, 'nova', 'ADVISORY'),

-- III. LEADERSHIP & INFLUENCE (AR-033 to AR-048)
('AR-033', 'The Leader', 'Guides collective energy toward a shared mission with integrity and presence.', 'Leadership & Influence', 92, 94, 90, 90, 93, 15, 'orion', 'ADVISORY'),
('AR-034', 'The Commander', 'Executes high-stakes decisions and maintains operational control under extreme pressure.', 'Leadership & Influence', 94, 90, 85, 95, 92, 25, 'orion', 'ADVISORY'),
('AR-035', 'The Strategist', 'Aligns resources and actions toward long-term outcomes across complex environments.', 'Leadership & Influence', 95, 91, 90, 88, 95, 15, 'orion', 'ADVISORY'),
('AR-036', 'The Diplomat', 'Navigates differences between parties without sacrificing core principles.', 'Leadership & Influence', 90, 96, 95, 82, 91, 10, 'orion', 'ADVISORY'),
('AR-037', 'The Advocate', 'Champions causes, principles, and people with passionate conviction.', 'Leadership & Influence', 88, 92, 88, 90, 90, 20, 'orion', 'ADVISORY'),
('AR-038', 'The Mentor', 'Accelerates development in others through seasoned guidance and wisdom.', 'Leadership & Influence', 90, 96, 92, 85, 93, 5, 'orion', 'ADVISORY'),
('AR-039', 'The Teacher', 'Converts knowledge and experience into structured understanding that others can use.', 'Leadership & Influence', 89, 94, 90, 85, 90, 5, 'orion', 'ADVISORY'),
('AR-040', 'The Guide', 'Illumines the path through unfamiliar territory with steady, grounded presence.', 'Leadership & Influence', 88, 95, 92, 85, 91, 10, 'orion', 'ADVISORY'),
('AR-041', 'The Protector', 'Defends people, values, ecosystems, and principles worth preserving.', 'Leadership & Influence', 88, 98, 85, 85, 89, 20, 'orion', 'ADVISORY'),
('AR-042', 'The Steward', 'Takes responsibility for resources, land, knowledge, wealth, and future generations.', 'Leadership & Influence', 90, 98, 92, 85, 93, 10, 'orion', 'ADVISORY'),
('AR-043', 'The Organizer', 'Brings order, structure, and operational rhythm to chaotic initiatives.', 'Leadership & Influence', 91, 92, 90, 88, 90, 10, 'orion', 'ADVISORY'),
('AR-044', 'The Mobilizer', 'Rallies people and capital into unified, immediate action.', 'Leadership & Influence', 90, 88, 88, 95, 91, 20, 'orion', 'ADVISORY'),
('AR-045', 'The Negotiator', 'Reaches optimal agreements by aligning opposing incentives and interests.', 'Leadership & Influence', 91, 90, 90, 88, 92, 15, 'orion', 'ADVISORY'),
('AR-046', 'The Influencer', 'Shapes public perception, cultural norms, and collective behavior.', 'Leadership & Influence', 87, 85, 86, 92, 88, 25, 'orion', 'ADVISORY'),
('AR-047', 'The Founder', 'Initiates something entirely new and accepts responsibility for bringing it into existence.', 'Leadership & Influence', 93, 89, 88, 95, 95, 25, 'orion', 'ADVISORY'),
('AR-048', 'The Changemaker', 'Disrupts stagnant systems to instigate positive, systemic evolution.', 'Leadership & Influence', 90, 86, 85, 95, 92, 30, 'orion', 'ADVISORY'),

-- IV. RELATIONSHIP & CONNECTION (AR-049 to AR-064)
('AR-049', 'The Connector', 'Introduces people and opportunities that would otherwise remain separate.', 'Relationship & Connection', 88, 92, 98, 90, 91, 10, 'seren', 'ADVISORY'),
('AR-050', 'The Nurturer', 'Protects growth through care, patience, nourishment, and emotional presence.', 'Relationship & Connection', 86, 96, 94, 82, 90, 5, 'seren', 'ADVISORY'),
('AR-051', 'The Caregiver', 'Provides dedicated, compassionate support during times of vulnerability.', 'Relationship & Connection', 87, 98, 95, 80, 91, 5, 'seren', 'ADVISORY'),
('AR-052', 'The Companion', 'Creates safety and belonging through loyal, steadfast presence.', 'Relationship & Connection', 86, 95, 94, 80, 89, 5, 'seren', 'ADVISORY'),
('AR-053', 'The Harmonizer', 'Balances emotional and energetic friction to maintain relational flow.', 'Relationship & Connection', 88, 94, 96, 82, 90, 5, 'seren', 'ADVISORY'),
('AR-054', 'The Peacemaker', 'Creates harmony between people, perspectives, communities, and opposing forces.', 'Relationship & Connection', 85, 95, 95, 80, 90, 5, 'seren', 'ADVISORY'),
('AR-055', 'The Empath', 'Senses and translates subtle emotional undercurrents across human networks.', 'Relationship & Connection', 87, 92, 92, 85, 91, 10, 'seren', 'ADVISORY'),
('AR-056', 'The Listener', 'Holds immaculate space for others to be heard and understood completely.', 'Relationship & Connection', 89, 98, 95, 78, 92, 5, 'seren', 'ADVISORY'),
('AR-057', 'The Beloved', 'Embodies receptivity, openness, and the magnetic grace to receive love and support.', 'Relationship & Connection', 84, 90, 92, 80, 88, 10, 'seren', 'ADVISORY'),
('AR-058', 'The Ally', 'Stands firmly beside others in shared pursuit of mutual objectives.', 'Relationship & Connection', 89, 96, 94, 85, 91, 10, 'seren', 'ADVISORY'),
('AR-059', 'The Bridge', 'Connects worlds, disciplines, communities, or opposing viewpoints.', 'Relationship & Connection', 91, 94, 96, 88, 93, 10, 'seren', 'ADVISORY'),
('AR-060', 'The Community Builder', 'Creates environments where people know, support, and contribute to one another.', 'Relationship & Connection', 90, 93, 97, 88, 92, 10, 'seren', 'ADVISORY'),
('AR-061', 'The Host', 'Creates spaces where people feel welcomed, nourished, and connected.', 'Relationship & Connection', 88, 95, 95, 85, 90, 5, 'seren', 'ADVISORY'),
('AR-062', 'The Collaborator', 'Thrives within collective intelligence to co-create superior outcomes.', 'Relationship & Connection', 90, 92, 96, 88, 92, 10, 'seren', 'ADVISORY'),
('AR-063', 'The Mirror', 'Reflects unvarnished truth back to individuals so they can see themselves clearly.', 'Relationship & Connection', 91, 90, 88, 86, 94, 15, 'seren', 'ADVISORY'),
('AR-064', 'The Devotee', 'Gives sustained attention, loyalty, and reverence to a higher purpose or partner.', 'Relationship & Connection', 86, 96, 90, 85, 90, 10, 'seren', 'ADVISORY'),

-- V. PURPOSE & MEANING (AR-065 to AR-080)
('AR-065', 'The Pilgrim', 'Treats life as a meaningful journey of transformation rather than a destination.', 'Purpose & Meaning', 88, 90, 88, 85, 95, 15, 'quest', 'ADVISORY'),
('AR-066', 'The Servant', 'Measures success by how much capacity and freedom others gain through service.', 'Purpose & Meaning', 87, 98, 92, 82, 91, 5, 'quest', 'ADVISORY'),
('AR-067', 'The Humanitarian', 'Dedicates energy toward alleviating suffering and elevating human dignity globally.', 'Purpose & Meaning', 88, 96, 90, 85, 92, 15, 'quest', 'ADVISORY'),
('AR-068', 'The Healer', 'Restores what is wounded, fragmented, depleted, or disconnected.', 'Purpose & Meaning', 88, 95, 85, 85, 90, 10, 'quest', 'ADVISORY'),
('AR-069', 'The Messenger', 'Carries important ideas between people, cultures, and generations.', 'Purpose & Meaning', 87, 91, 90, 88, 89, 10, 'quest', 'ADVISORY'),
('AR-070', 'The Oracle', 'Recognizes emerging patterns and possibilities before they become visible to everyone.', 'Purpose & Meaning', 95, 88, 88, 92, 96, 25, 'quest', 'ADVISORY'),
('AR-071', 'The Truth-Seeker', 'Strips away illusion to uncover fundamental principles of reality.', 'Purpose & Meaning', 92, 90, 85, 88, 95, 15, 'quest', 'ADVISORY'),
('AR-072', 'The Wisdom Keeper', 'Preserves ancient insights and modern realizations for future generations.', 'Purpose & Meaning', 94, 97, 90, 80, 96, 5, 'quest', 'ADVISORY'),
('AR-073', 'The Spiritualist', 'Explores consciousness, divine order, and non-material dimensions of being.', 'Purpose & Meaning', 88, 89, 85, 82, 94, 15, 'quest', 'ADVISORY'),
('AR-074', 'The Light-Bringer', 'Brings clarity, illumination, and awareness into darkened or confused spaces.', 'Purpose & Meaning', 91, 92, 90, 90, 93, 15, 'quest', 'ADVISORY'),
('AR-075', 'The Wayfinder', 'Finds practical routes through existential uncertainty and helps others navigate.', 'Purpose & Meaning', 92, 94, 91, 88, 94, 15, 'quest', 'ADVISORY'),
('AR-076', 'The Liberator', 'Helps people break free from limiting beliefs, systems, and circumstances.', 'Purpose & Meaning', 91, 88, 86, 94, 95, 30, 'quest', 'ADVISORY'),
('AR-077', 'The Justice-Seeker', 'Fights for fairness, equity, and alignment with universal moral laws.', 'Purpose & Meaning', 90, 92, 88, 90, 92, 25, 'quest', 'ADVISORY'),
('AR-078', 'The Purpose Messenger', 'Articulates mission and calling with resonance that moves crowds.', 'Purpose & Meaning', 89, 90, 90, 90, 91, 15, 'quest', 'ADVISORY'),
('AR-079', 'The Vision Keeper', 'Protects the original purpose and spirit of a movement or organization.', 'Purpose & Meaning', 91, 95, 92, 85, 93, 10, 'quest', 'ADVISORY'),
('AR-080', 'The Purpose Bearer', 'Carries the energetic weight of a mission through difficult transitions.', 'Purpose & Meaning', 92, 94, 89, 88, 94, 20, 'quest', 'ADVISORY'),

-- VI. GROWTH & TRANSFORMATION (AR-081 to AR-096)
('AR-081', 'The Phoenix', 'Rebuilds identity and purpose after profound endings or transformation.', 'Growth & Transformation', 93, 85, 85, 96, 99, 35, 'alaric', 'ADVISORY'),
('AR-082', 'The Transformer', 'Deliberately evolves beliefs, behaviors, relationships, and environments.', 'Growth & Transformation', 92, 88, 88, 94, 96, 25, 'alaric', 'ADVISORY'),
('AR-083', 'The Evolver', 'Treats personal and collective evolution as an ongoing life responsibility.', 'Growth & Transformation', 91, 90, 90, 90, 97, 15, 'alaric', 'ADVISORY'),
('AR-084', 'The Rebuilder', 'Constructs resilient new systems and lives out of the debris of the old.', 'Growth & Transformation', 92, 91, 90, 90, 94, 20, 'alaric', 'ADVISORY'),
('AR-085', 'The Survivor', 'Protects life and finds a path forward despite severe systemic constraints.', 'Growth & Transformation', 86, 92, 82, 88, 90, 30, 'alaric', 'ADVISORY'),
('AR-086', 'The Initiator', 'Sparks new cycles, ventures, and phases of personal growth.', 'Growth & Transformation', 90, 86, 88, 95, 92, 25, 'alaric', 'ADVISORY'),
('AR-087', 'The Threshold Walker', 'Operates fluidly between old paradigms and emerging realities.', 'Growth & Transformation', 93, 89, 90, 92, 96, 25, 'alaric', 'ADVISORY'),
('AR-088', 'The Challenger', 'Pushes people beyond comfort zones into actualized potential.', 'Growth & Transformation', 89, 85, 82, 94, 91, 30, 'alaric', 'ADVISORY'),
('AR-089', 'The Explorer', 'Expands beyond familiar boundaries in search of experience and knowledge.', 'Growth & Transformation', 85, 82, 85, 92, 90, 30, 'alaric', 'ADVISORY'),
('AR-090', 'The Risk-Taker', 'Steps willingly into high uncertainty for asymmetric growth and reward.', 'Growth & Transformation', 88, 80, 80, 96, 93, 45, 'alaric', 'ADVISORY'),
('AR-091', 'The Learner', 'Remains humble, curious, and hungry to assimilate new insights continuously.', 'Growth & Transformation', 90, 92, 92, 90, 96, 10, 'alaric', 'ADVISORY'),
('AR-092', 'The Student', 'Absorbs discipline, mastery, and craft from teachers and life experience.', 'Growth & Transformation', 88, 90, 90, 88, 94, 10, 'alaric', 'ADVISORY'),
('AR-093', 'The Awakener', 'Sparks recognition in others that they are capable of vastly more.', 'Growth & Transformation', 92, 88, 89, 95, 95, 20, 'alaric', 'ADVISORY'),
('AR-094', 'The Integrator', 'Brings fragmented identities and competing internal drives into alignment.', 'Growth & Transformation', 93, 92, 94, 88, 95, 10, 'alaric', 'ADVISORY'),
('AR-095', 'The Renewer', 'Breathes fresh vitality into tired projects, relationships, and institutions.', 'Growth & Transformation', 90, 90, 92, 90, 92, 15, 'alaric', 'ADVISORY'),
('AR-096', 'The Transcender', 'Rises above ordinary limitations into higher states of realization and capacity.', 'Growth & Transformation', 96, 90, 90, 95, 99, 20, 'alaric', 'ADVISORY'),

-- VII. STRATEGY & ACHIEVEMENT (AR-097 to AR-112)
('AR-097', 'The Achiever', 'Converts ambition into measurable milestones and exceptional outcomes.', 'Strategy & Achievement', 92, 90, 85, 94, 92, 20, 'axel', 'ADVISORY'),
('AR-098', 'The Builder', 'Creates practical things that improve life and endure beyond the individual.', 'Strategy & Achievement', 93, 91, 90, 90, 93, 10, 'axel', 'ADVISORY'),
('AR-099', 'The Operator', 'Ensures daily execution runs smoothly, efficiently, and without friction.', 'Strategy & Achievement', 94, 95, 92, 85, 90, 5, 'axel', 'ADVISORY'),
('AR-100', 'The Executor', 'Turns strategic directives into immediate, flawless tactical reality.', 'Strategy & Achievement', 95, 92, 89, 92, 91, 15, 'axel', 'ADVISORY'),
('AR-101', 'The Analyst', 'Uses data, logic, and meticulous examination to understand complex realities.', 'Strategy & Achievement', 96, 94, 88, 80, 92, 5, 'axel', 'ADVISORY'),
('AR-102', 'The Planner', 'Anticipates contingencies and plots sequential steps toward complex goals.', 'Strategy & Achievement', 94, 95, 90, 82, 91, 5, 'axel', 'ADVISORY'),
('AR-103', 'The Optimizer', 'Constantly refines systems for maximum output with minimal waste.', 'Strategy & Achievement', 95, 92, 90, 88, 93, 10, 'axel', 'ADVISORY'),
('AR-104', 'The Entrepreneur', 'Converts opportunity, resources, and creativity into sustainable value.', 'Strategy & Achievement', 93, 88, 88, 95, 95, 30, 'axel', 'ADVISORY'),
('AR-105', 'The Investor', 'Allocates capital and attention toward high-yield futures worth backing.', 'Strategy & Achievement', 94, 90, 89, 88, 94, 20, 'axel', 'ADVISORY'),
('AR-106', 'The Competitor', 'Thrives in rivalry, benchmarking excellence against the best in the arena.', 'Strategy & Achievement', 91, 86, 82, 94, 90, 30, 'axel', 'ADVISORY'),
('AR-107', 'The Mastermind', 'Engineers intricate master-plans integrating people, capital, and timing.', 'Strategy & Achievement', 96, 91, 91, 90, 96, 15, 'axel', 'ADVISORY'),
('AR-108', 'The Problem-Solver', 'Diagnoses roadblocks and formulates immediate, effective fixes.', 'Strategy & Achievement', 95, 93, 90, 90, 92, 10, 'axel', 'ADVISORY'),
('AR-109', 'The Opportunity Seeker', 'Scans horizons to detect hidden openings and emerging tailwinds.', 'Strategy & Achievement', 92, 88, 88, 93, 93, 25, 'axel', 'ADVISORY'),
('AR-110', 'The Systems Builder', 'Constructs robust automated architectures that scale effortlessly.', 'Strategy & Achievement', 96, 92, 94, 88, 95, 10, 'axel', 'ADVISORY'),
('AR-111', 'The Resource Strategist', 'Allocates scarce assets with maximum leverage and return.', 'Strategy & Achievement', 95, 93, 90, 88, 93, 10, 'axel', 'ADVISORY'),
('AR-112', 'The Legacy Builder', 'Constructs lasting institutions, wealth structures, and cultural monuments.', 'Strategy & Achievement', 94, 96, 92, 85, 96, 10, 'axel', 'ADVISORY'),

-- VIII. INTEGRATION & EVOLUTION (AR-113 to AR-128)
('AR-113', 'The Aligned One', 'Maintains flawless congruence between inner truth and outer action.', 'Integration & Evolution', 95, 96, 94, 88, 97, 5, 'eden', 'ADVISORY'),
('AR-114', 'The Whole Self', 'Embraces all psychological fragments into a unified, integrated human expression.', 'Integration & Evolution', 94, 95, 95, 86, 97, 5, 'eden', 'ADVISORY'),
('AR-115', 'The Synthesizer', 'Blends disparate domains of knowledge into breakthrough frameworks.', 'Integration & Evolution', 96, 92, 94, 90, 97, 10, 'eden', 'ADVISORY'),
('AR-116', 'The Pattern Seer', 'Identifies macro trends and hidden synchronicities across vast data sets.', 'Integration & Evolution', 97, 90, 92, 92, 98, 15, 'eden', 'ADVISORY'),
('AR-117', 'The Conscious Creator', 'Wields intention, focus, and energy to manifest desired realities deliberately.', 'Integration & Evolution', 95, 92, 92, 94, 98, 15, 'eden', 'ADVISORY'),
('AR-118', 'The Evolutionary', 'Drives conscious adaptation at the cutting edge of human capability.', 'Integration & Evolution', 96, 91, 92, 95, 99, 20, 'eden', 'ADVISORY'),
('AR-119', 'The Systems Thinker', 'Perceives feedback loops, leverage points, and second-order consequences.', 'Integration & Evolution', 97, 94, 95, 88, 97, 5, 'eden', 'ADVISORY'),
('AR-120', 'The Reality Shaper', 'Bends circumstances through sheer energetic coherence and strategic execution.', 'Integration & Evolution', 96, 89, 90, 96, 98, 25, 'eden', 'ADVISORY'),
('AR-121', 'The Future Builder', 'Architects civilizations, technologies, and paradigms for generations unborn.', 'Integration & Evolution', 97, 93, 94, 92, 99, 15, 'eden', 'ADVISORY'),
('AR-122', 'The Wisdom Architect', 'Encodes lived experience into universal mental models and frameworks.', 'Integration & Evolution', 96, 96, 93, 86, 98, 5, 'eden', 'ADVISORY'),
('AR-123', 'The Collective Mind', 'Operates seamlessly as a node within networked human and machine intelligence.', 'Integration & Evolution', 98, 95, 98, 92, 99, 10, 'eden', 'ADVISORY'),
('AR-124', 'The Regenerator', 'Actively restores depleted biological, social, and economic systems.', 'Integration & Evolution', 94, 97, 95, 88, 97, 10, 'eden', 'ADVISORY'),
('AR-125', 'The Transmitter', 'Broadcasts high-frequency wisdom and codes of mastery across networks.', 'Integration & Evolution', 95, 92, 93, 94, 98, 15, 'eden', 'ADVISORY'),
('AR-126', 'The Legacy Weaver', 'Connects past ancestral wisdom with future possibilities in the present moment.', 'Integration & Evolution', 94, 96, 94, 88, 97, 10, 'eden', 'ADVISORY'),
('AR-127', 'The Integrative Intelligence', 'Unifies emotional, somatic, cognitive, and spiritual intelligence into one flow.', 'Integration & Evolution', 97, 95, 96, 90, 99, 5, 'eden', 'ADVISORY'),
('AR-128', 'The Aetherial', 'Embodies the subtle, unmanifest essence connecting all things across dimensions.', 'Integration & Evolution', 99, 98, 99, 95, 100, 5, 'eden', 'ADVISORY')
ON CONFLICT (archetype_id) DO UPDATE SET 
  archetype_name = EXCLUDED.archetype_name, 
  description = EXCLUDED.description,
  category = EXCLUDED.category;
