import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PDFDocument from 'pdfkit'

/**
 * GET /api/zuri/essence/export?format=txt|pdf
 * Exports the current user's essence board data.
 */
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const format = searchParams.get('format') || 'txt'

  if (!['txt', 'pdf'].includes(format)) {
    return NextResponse.json({ error: 'Invalid format. Use txt or pdf.' }, { status: 400 })
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  // Fetch essence intelligence items for the user
  const { data: _items } = await supabase
    .from('essintelligence')
    .select('*')
    .eq('client_id', user.id)
    .order('created_at', { ascending: false })
    .limit(20)
  const items = (_items || []) as any[]

  // Fetch user profile / blueprint info
  const { data: twin } = await supabase
    .from('client_twins')
    .select('metadata')
    .eq('client_id', user.id)
    .maybeSingle()

  const blueprintMeta = (twin?.metadata as any)?.blueprint?.core
  const archetype = blueprintMeta?.archetype || 'Unknown'
  const overallScore = blueprintMeta?.overallScore || 0

  const now = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  })

  if (format === 'txt') {
    let text = `╔══════════════════════════════════════════════════════════╗\n`
    text += `║          ESSENCE INTELLIGENCE BOARD                     ║\n`
    text += `╚══════════════════════════════════════════════════════════╝\n\n`
    text += `Date: ${now}\n`
    text += `Archetype: ${archetype}\n`
    text += `Blueprint Score: ${overallScore}/100\n`
    text += `${'═'.repeat(55)}\n\n`

    if (!items || items.length === 0) {
      text += `No essence intelligence items yet. Complete your blueprint\n`
      text += `assessment to generate personalized intelligence.\n`
    } else {
      text += `INTELLIGENCE ITEMS (${items.length}):\n`
      text += `${'─'.repeat(55)}\n\n`
      for (const item of items) {
        const type = (item.type || 'general').replace(/_/g, ' ')
        text += `[${type.toUpperCase()}] [${item.priority || 'medium'}] [${item.status}]\n`
        text += `${item.content}\n`
        text += `\n`
      }
    }

    text += `${'═'.repeat(55)}\n`
    text += `Generated by Evolved Eden Intelligence Platform\n`

    return new NextResponse(text, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="essence-board-${now.replace(/[/, ]/g, '-')}.txt"`,
      },
    })
  }

  if (format === 'pdf') {
    const chunks: Buffer[] = []
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: { Title: 'Essence Intelligence Board', Author: 'Evolved Eden' },
    })

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))

    doc.fontSize(20).font('Helvetica-Bold').text('Essence Intelligence Board', { align: 'center' })
    doc.moveDown(0.3)
    doc.fontSize(10).font('Helvetica').text(`Date: ${now}`, { align: 'center' })
    doc.text(`Archetype: ${archetype}  |  Blueprint Score: ${overallScore}/100`, { align: 'center' })
    doc.moveDown(0.5)
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke()
    doc.moveDown(0.5)

    if (!items || items.length === 0) {
      doc.fontSize(11).text('No essence intelligence items yet. Complete your blueprint assessment to generate personalized intelligence.')
    } else {
      for (const item of items) {
        if (doc.y > 700) doc.addPage()

        const type = (item.type || 'general').replace(/_/g, ' ')
        const priority = item.priority || 'medium'
        const status = item.status || 'pending'

        doc.fontSize(12).font('Helvetica-Bold').text(`${type.toUpperCase()}`, { continued: true })
        doc.fontSize(10).font('Helvetica').fillColor('#666666').text(`  [${priority}] [${status}]`)
        doc.fillColor('#000000')
        doc.fontSize(10).font('Helvetica').text(item.content, { align: 'justify' })
        doc.moveDown(0.4)
      }
    }

    doc.moveDown(1)
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke()
    doc.moveDown(0.3)
    doc.fontSize(9).fillColor('#999999').text('Generated by Evolved Eden Intelligence Platform', { align: 'center' })

    doc.end()

    const pdfBuffer = await new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)))
    })

    return new NextResponse(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="essence-board-${now.replace(/[/, ]/g, '-')}.pdf"`,
      },
    })
  }

  return NextResponse.json({ error: 'Unsupported format' }, { status: 400 })
}
