import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { Document, Packer, HeadingLevel, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle } from 'docx'
import PDFDocument from 'pdfkit'

type SystemData = {
  slug: string
  name: string
  tagline: string | null
  description: string | null
  system_number: number
  domain_key: string
}

type SectionEntry = {
  key: string
  system_number: number
  name: string
  order: number
}

type BlueprintData = {
  key: string
  name: string
  description: string | null
  sections_json: Record<string, SectionEntry>
  template_json: Record<string, any>
}

/**
 * GET /api/blueprint/export?template=blueprint_core&format=txt
 */
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const templateKey = searchParams.get('template')
  const format = searchParams.get('format') || 'txt'

  if (!templateKey) {
    return NextResponse.json({ error: 'Missing template parameter' }, { status: 400 })
  }

  if (!['txt', 'docx', 'pdf'].includes(format)) {
    return NextResponse.json({ error: 'Invalid format. Use txt, docx, or pdf.' }, { status: 400 })
  }

  const supabase = await createClient()

  // Fetch blueprint template
  const { data: blueprint, error: bpError } = await supabase
    .from('blueprint_templates')
    .select('*')
    .eq('key', templateKey)
    .single()

  if (bpError || !blueprint) {
    return NextResponse.json({ error: 'Blueprint template not found' }, { status: 404 })
  }

  const bp = blueprint as BlueprintData

  // Collect all system slugs from sections_json
  const systemSlugs: string[] = Object.values(bp.sections_json || {}).map((s: SectionEntry) => s.key)

  // Fetch system data
  const { data: systems } = await supabase
    .from('omnigrid_intelligence_system')
    .select('slug, name, tagline, description, system_number, domain_key')
    .in('slug', systemSlugs)
    .order('system_number')

  const sysMap = new Map<string, SystemData>()
  for (const sys of (systems || []) as SystemData[]) {
    sysMap.set(sys.slug, sys)
  }

  // Build ordered sections
  const sections = Object.values(bp.sections_json || {})
    .sort((a: SectionEntry, b: SectionEntry) => a.order - b.order)

  // Group by domain for better readability
  const domainGroups: Record<string, { domain: string; systems: SystemData[] }> = {}
  for (const entry of sections) {
    const sys = sysMap.get(entry.key)
    if (!sys) continue
    const domain = sys.domain_key || 'uncategorized'
    if (!domainGroups[domain]) {
      domainGroups[domain] = { domain, systems: [] }
    }
    domainGroups[domain].systems.push(sys)
  }

  const title = bp.name
  const description = bp.description || ''

  // ── Format: TXT ─────────────────────────────────────────
  if (format === 'txt') {
    let text = `╔══════════════════════════════════════════════════════════════════╗\n`
    text += `║  ${title.padEnd(61)}║\n`
    text += `╚══════════════════════════════════════════════════════════════════╝\n\n`
    if (description) text += description + '\n\n'
    text += `Total Systems: ${systemSlugs.length}\n`
    text += `${'═'.repeat(70)}\n\n`

    for (const [domKey, group] of Object.entries(domainGroups)) {
      text += `── ${domKey.replace(/_/g, ' ').toUpperCase()} ──\n`
      text += `${'─'.repeat(50)}\n`
      for (const sys of group.systems) {
        text += `\n  ${sys.name}`
        if (sys.tagline) text += `\n  → ${sys.tagline}`
        if (sys.description) {
          const lines = sys.description.match(/.{1,72}(?:\s|$)/g) || []
          for (const line of lines) {
            text += `\n  ${line.trim()}`
          }
        }
        text += '\n'
      }
      text += '\n'
    }

    text += `${'═'.repeat(70)}\n`
    text += `Generated by Evolved Eden Intelligence Platform\n`

    return new NextResponse(text, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${bp.key.replace(/_/g, '-')}-blueprint.txt"`,
      },
    })
  }

  // ── Format: DOCX ─────────────────────────────────────────
  if (format === 'docx') {
    const children: any[] = []

    // Title
    children.push(
      new Paragraph({
        text: title,
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      })
    )

    if (description) {
      children.push(
        new Paragraph({
          text: description,
          spacing: { after: 200 },
        })
      )
    }

    children.push(
      new Paragraph({
        text: `Total Systems: ${systemSlugs.length}`,
        spacing: { after: 200 },
        thematicBreak: true,
      })
    )

    // Sections
    for (const [domKey, group] of Object.entries(domainGroups)) {
      children.push(
        new Paragraph({
          text: domKey.replace(/_/g, ' ').toUpperCase(),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 200 },
        })
      )

      for (const sys of group.systems) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: sys.name, bold: true, size: 24 }),
            ],
            spacing: { before: 200, after: 60 },
          })
        )

        if (sys.tagline) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({ text: sys.tagline, italics: true, color: '666666' }),
              ],
              spacing: { after: 60 },
            })
          )
        }

        if (sys.description) {
          children.push(
            new Paragraph({
              text: sys.description,
              spacing: { after: 200 },
            })
          )
        }
      }
    }

    const doc = new Document({
      title: title,
      description: description || undefined,
      styles: {
        default: {
          document: {
            run: { size: 22, font: 'Calibri' },
          },
        },
      },
      sections: [{ children }],
    })

    const buffer = await Packer.toBuffer(doc)

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${bp.key.replace(/_/g, '-')}-blueprint.docx"`,
      },
    })
  }

  // ── Format: PDF ──────────────────────────────────────────
  if (format === 'pdf') {
    const chunks: Buffer[] = []
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: title,
        Author: 'Evolved Eden Intelligence Platform',
      },
    })

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))

    // Title
    doc.fontSize(22).font('Helvetica-Bold').text(title, { align: 'center' })
    doc.moveDown(0.5)

    if (description) {
      doc.fontSize(11).font('Helvetica').text(description, { align: 'left' })
      doc.moveDown(0.5)
    }

    doc.fontSize(10).text(`Total Systems: ${systemSlugs.length}`, { align: 'left' })
    doc.moveDown(0.5)

    // Draw a line
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke()
    doc.moveDown(0.5)

    // Sections
    for (const [domKey, group] of Object.entries(domainGroups)) {
      // Check if we need a new page (don't start section at bottom)
      if (doc.y > 650) doc.addPage()

      doc.fontSize(16).font('Helvetica-Bold').text(domKey.replace(/_/g, ' ').toUpperCase())
      doc.moveDown(0.3)

      for (const sys of group.systems) {
        if (doc.y > 700) doc.addPage()

        doc.fontSize(12).font('Helvetica-Bold').text(sys.name)
        doc.moveDown(0.1)

        if (sys.tagline) {
          doc.fontSize(10).font('Helvetica-Oblique').fillColor('#666666').text(sys.tagline)
          doc.fillColor('#000000')
          doc.moveDown(0.1)
        }

        if (sys.description) {
          doc.fontSize(10).font('Helvetica').text(sys.description, {
            align: 'justify',
          })
          doc.moveDown(0.3)
        }
      }
    }

    // Footer
    doc.moveDown(1)
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke()
    doc.moveDown(0.3)
    doc.fontSize(9).fillColor('#999999').text('Generated by Evolved Eden Intelligence Platform', { align: 'center' })

    doc.end()

    // Wait for PDF to finish
    const pdfBuffer = await new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)))
    })

    return new NextResponse(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${bp.key.replace(/_/g, '-')}-blueprint.pdf"`,
      },
    })
  }

  return NextResponse.json({ error: 'Unsupported format' }, { status: 400 })
}
