-- Starting set of real, client-facing os_package workflows grounded in
-- actual agent/vertical/swarm data (role_type + vertical distribution
-- checked before writing these): Founder OS (corporate-vertical + hiring),
-- Creator OS (arts/media-vertical), Business OS (commerce/corporate/
-- finance-vertical, generalizes the pre-existing real-estate demo lead-
-- nurture pattern), Agency OS (CROSS_SYSTEM agents + swarm_catalog multi-
-- tenant rollup), Family OS (luxury-vertical + CRISIS-capable routing),
-- Wellness OS (health/mental_health-vertical, promotes the pre-existing
-- health_wellness_longevity demo rows into real scheduled workflows).
-- Personal OS deliberately gets none of these -- core standard_in_all_os
-- workflows are already everything it needs; no CRM/campaign tooling.

insert into public.workflows
  (wf_code, phase, sequence, name, category, applicable_os, purpose, trigger_summary, input_schema, output_schema, supabase_tables, external_integrations, error_handling, scope, lifecycle_status, version, is_active, run_status, standard_in_all_os)
values
('WF-801',8,1,'Founder Weekly KPI & Investor Update','automation','{"founder_os"}'::text[],'Compiles the week''s essence board activity, agent-run outputs, and any manually-entered KPIs into a single shareable update -- the recurring ''founder update'' most founders currently write by hand.','Scheduled: weekly, Friday','{"client_id": "uuid"}'::jsonb,'{"update_doc_url": "string"}'::jsonb,'{"client_essence_actions","clients"}'::text[],'{"Resend/SMTP","Google Docs API (optional)"}'::text[],'If KPI data is incomplete, ship the update with what''s available and flag the gaps rather than blocking.','os_package','documented',1,true,'draft',false),
('WF-802',8,2,'Founder Hiring Pipeline Automation','automation','{"founder_os"}'::text[],'Routes inbound candidate applications to the relevant corporate-vertical agent for first-pass screening, and schedules qualified candidates directly onto the founder''s calendar.','Webhook: new application (ATS or a simple form endpoint)','{"candidate_email": "string", "role": "string"}'::jsonb,'{"screened": "boolean", "meeting_scheduled": "boolean"}'::jsonb,'{"clients"}'::text[],'{"Calendar API","ATS webhook"}'::text[],'Never auto-rejects a candidate -- screening surfaces a recommendation, a human makes the call.','os_package','documented',1,true,'draft',false),
('WF-901',9,1,'Creator Content Calendar Sync','automation','{"creator_os"}'::text[],'Turns a content brief into a scheduled posting calendar across the creator''s connected channels, using the arts/media-vertical agent pool for draft copy per platform.','Manual trigger from the Creator dashboard, or weekly for evergreen content','{"brief": "string", "channels": "string[]"}'::jsonb,'{"posts_scheduled": "int"}'::jsonb,'{"clients"}'::text[],'{"Canva API","social platform APIs"}'::text[],'Every post requires explicit creator approval before it goes live -- never auto-publishes.','os_package','documented',1,true,'draft',false),
('WF-902',9,2,'Creator Payout & Royalty Tracker','automation','{"creator_os"}'::text[],'Surfaces upcoming and completed marketplace payouts (feeds WF-304''s batch) in the creator''s own dashboard so they''re never guessing when they''ll get paid.','Scheduled: daily','{}'::jsonb,'{"pending_payout_total": "numeric"}'::jsonb,'{"catalog_items"}'::text[],'{"Stripe Connect"}'::text[],'Report-only; the actual payout logic lives in WF-304.','os_package','documented',1,true,'draft',false),
('WF-1001',10,1,'Business Lead Nurture & Qualification','intake','{"business_os"}'::text[],'Generalizes the pattern already sketched in the pre-existing real-estate demo workflow (Lead Capture -> Qualification -> Scheduling -> Follow-up) into a vertical-agnostic version for any Business OS client, using commerce/corporate-vertical agents for scoring.','Webhook: new lead (form submission, HubSpot, etc.)','{"lead_email": "string", "source": "string"}'::jsonb,'{"qualified": "boolean", "score": "int"}'::jsonb,'{"clients"}'::text[],'{"HubSpot/CRM webhook"}'::text[],'Unscored leads default to manual review queue rather than being silently dropped.','os_package','documented',1,true,'draft',false),
('WF-1002',10,2,'Business Invoice & AR/AP Automation','automation','{"business_os"}'::text[],'Automates invoice reminders and AR/AP reconciliation using finance-vertical agents -- ties directly into WF-302''s dunning sequence for overdue accounts.','Scheduled: daily','{}'::jsonb,'{"invoices_processed": "int"}'::jsonb,'{"clients"}'::text[],'{"QuickBooks/Stripe API"}'::text[],'Reconciliation mismatches are flagged for the client''s own bookkeeper, never auto-corrected.','os_package','documented',1,true,'draft',false),
('WF-1101',11,1,'Agency Multi-Client Swarm Dashboard Sync','swarm','{"agency_os"}'::text[],'Rolls up swarm activity and health scores (swarm_catalog.health_score/mas_score) across every client account an agency manages into one dashboard -- the multi-tenant view a single-client OS doesn''t need.','Scheduled: hourly','{}'::jsonb,'{"clients_summarized": "int"}'::jsonb,'{"swarm_catalog","client_deployed_swarms"}'::text[],'{}'::text[],'A single client''s swarm failure must not block the rollup for the rest of the agency''s roster.','os_package','documented',1,true,'draft',false),
('WF-1102',11,2,'Agency White-Label Report Generator','automation','{"agency_os"}'::text[],'Generates a client-ready, white-labeled version of essence board / swarm activity for the agency to send to ITS OWN clients under its own brand -- uses the brand kit system already built for agent execution.','Manual trigger or scheduled monthly per managed client','{"managed_client_id": "uuid"}'::jsonb,'{"report_url": "string"}'::jsonb,'{"clients","client_essence_actions"}'::text[],'{}'::text[],'Falls back to the agency''s default brand kit if the managed client has none configured.','os_package','documented',1,true,'draft',false),
('WF-1201',12,1,'Family Office Concierge Request Router','service','{"family_os"}'::text[],'Routes an incoming family-office request (travel, health, legal, financial) to the right luxury-vertical or crisis-capable agent based on urgency and category, matching the existing luxury_hospitality demo pattern but generalized beyond hospitality.','Inbound request (email, form, or concierge chat)','{"request_text": "string", "urgency": "string"}'::jsonb,'{"routed_to_agent_id": "string"}'::jsonb,'{"clients"}'::text[],'{"Email/SMS intake"}'::text[],'Anything flagged urgent/crisis routes to a human concierge immediately in parallel with the agent -- never agent-only for time-sensitive family matters.','os_package','documented',1,true,'draft',false),
('WF-1202',12,2,'Family Legacy & Estate Planning Tracker','assessment','{"family_os"}'::text[],'Tracks progress on legacy/estate planning milestones across a family unit (multiple client_twins under one organization) -- a genuinely multi-person workflow Personal OS''s single-user model doesn''t need.','Scheduled: monthly review','{"organization_id": "uuid"}'::jsonb,'{"milestones_complete": "int", "milestones_pending": "int"}'::jsonb,'{"organizations","client_twins"}'::text[],'{}'::text[],'Report-only -- surfaces status to the family office lead, never auto-advances legal steps.','os_package','documented',1,true,'draft',false),
('WF-1301',13,1,'Wellness Client Retention & Check-In','automation','{"wellness_os"}'::text[],'Promotes the pattern already sketched in the pre-existing ''Retention Monitoring'' health_wellness_longevity demo row into a real, scheduled check-in cadence using health/mental_health-vertical agents.','Scheduled: per-client cadence based on treatment plan','{"client_id": "uuid"}'::jsonb,'{"check_in_sent": "boolean", "response_flagged": "boolean"}'::jsonb,'{"clients"}'::text[],'{"SMS/Email"}'::text[],'Any concerning response (self-reported symptom escalation, distress language) routes to a human practitioner immediately, never handled by the agent alone.','os_package','documented',1,true,'draft',false),
('WF-1302',13,2,'Wellness Treatment Intelligence Sync','assessment','{"wellness_os"}'::text[],'Promotes the pre-existing ''Treatment Intelligence'' health_wellness_longevity demo row -- keeps a practitioner''s treatment notes and the client''s essence board/blueprint in sync so recommendations reflect actual clinical context.','On treatment note update (practitioner-side)','{"client_id": "uuid", "note": "string"}'::jsonb,'{"synced": "boolean"}'::jsonb,'{"client_twins"}'::text[],'{"EHR/practice management API (practice-specific)"}'::text[],'Never overwrites practitioner clinical notes with AI-generated content -- one-directional sync into the essence context only.','os_package','documented',1,true,'draft',false);