import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { requireAdmin } from '@/lib/admin-auth'

/**
 * Admin deployment management
 * GET  — list all clients with their deployed agents
 * POST — deploy an agent to a client
 * DELETE — remove an agent deployment from a client
 */
export async function GET(req: NextRequest) {
  try {
    const auth = await requireAdmin()
    if (auth instanceof NextResponse) return auth
    const { searchParams } = new URL(req.url)
    const clientId = searchParams.get('client_id')

    // 1. Fetch deployed agents from client_deployed_agents
    let agentsQuery = supabaseAdmin
      .from('client_deployed_agents')
      .select('*')

    if (clientId) {
      agentsQuery = agentsQuery.eq('client_id', clientId)
    }

    const { data: deployedAgents, error: agentsError } = await agentsQuery.order('created_at', { ascending: false })
    if (agentsError) throw agentsError

    // 2. Collect unique client IDs and fetch client details in a separate query
    const clientIds = [...new Set((deployedAgents || []).map(a => a.client_id).filter(Boolean))]

    const { data: clientsData } = clientIds.length > 0
      ? await supabaseAdmin.from('clients').select('id, full_name, email, plan_tier_key, status').in('id', clientIds)
      : { data: [] }

    const clientMap = new Map((clientsData || []).map(c => [c.id, c]))

    // 3. Merge in code
    const byClient = new Map<string, { client: { id: string; full_name: string; email: string; plan_tier_key: string | null; status: string | null }; agents: any[] }>()

    for (const agent of deployedAgents || []) {
      const cid = agent.client_id
      if (!cid) continue

      if (!byClient.has(cid)) {
        const clientInfo = clientMap.get(cid)
        byClient.set(cid, {
          client: {
            id: cid,
            full_name: clientInfo?.full_name || 'Unknown',
            email: clientInfo?.email || '',
            plan_tier_key: clientInfo?.plan_tier_key || null,
            status: clientInfo?.status || null,
          },
          agents: [],
        })
      }
      byClient.get(cid)!.agents.push({
        id: agent.id,
        agent_id: agent.agent_id,
        agent_name: agent.agent_name,
        role_type: agent.role_type,
        status: agent.status,
      })
    }

    return NextResponse.json({ clients: Array.from(byClient.values()) })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  try {
    const auth = await requireAdmin()
    if (auth instanceof NextResponse) return auth
    const { client_id, agent_id, agent_name, role_type, action } = await req.json()

    if (!client_id) {
      return NextResponse.json({ error: 'client_id is required' }, { status: 400 })
    }

    if (action === 'add_agent') {
      if (!agent_id || !agent_name) {
        return NextResponse.json({ error: 'agent_id and agent_name required' }, { status: 400 })
      }

      // id is auto-generated by the DB default (gen_random_uuid)
      const { data, error } = await supabaseAdmin
        .from('client_deployed_agents')
        .insert({
          client_id,
          agent_id,
          agent_name,
          role_type: role_type || 'VERTICAL',
          status: 'active',
        })
        .select()
        .single()

      if (error) throw error

      // Fire-and-forget counter update (non-critical, errors suppressed)
      supabaseAdmin.from('clients').select('agent_deployments').eq('id', client_id).single()
        .then(({ data: clientRow }) => {
          supabaseAdmin.from('clients').update({ agent_deployments: (clientRow?.agent_deployments ?? 0) + 1 }).eq('id', client_id).then(() => {}, () => {})
        })
        .then(() => {}, () => {})

      return NextResponse.json({ success: true, agent: data })
    }

    return NextResponse.json({ error: 'Unknown action' }, { status: 400 })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const auth = await requireAdmin()
    if (auth instanceof NextResponse) return auth
    const { client_id, agent_id } = await req.json()
    if (!client_id || !agent_id) {
      return NextResponse.json({ error: 'client_id and agent_id required' }, { status: 400 })
    }

    const { data: deleted, error } = await supabaseAdmin
      .from('client_deployed_agents')
      .delete()
      .eq('client_id', client_id)
      .eq('agent_id', agent_id)
      .select()

    if (error) throw error

    // Fire-and-forget counter decrement
    if (deleted && deleted.length > 0) {
      supabaseAdmin.from('clients').select('agent_deployments').eq('id', client_id).single()
        .then(({ data: c }) => {
          supabaseAdmin.from('clients').update({ agent_deployments: Math.max((c?.agent_deployments ?? 1) - 1, 0) }).eq('id', client_id).then(() => {}, () => {})
        })
        .then(() => {}, () => {})
    }

    return NextResponse.json({ success: true })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
